### ISSUE TITLE
Is the feed broken?

### ISSUE THREAD

**Issue by secw** [fbis251/overwatch_news_feed#2]
Idk what's wrong, it just seem broken now

**Comment by fbis251** [comment]
Hey @secw what's the issue you're having specifically?

I just checked the feed against the page it's updated from (https://playoverwatch.com/en-us/game/patch-notes/pc/) and the feed is up to date

**Comment by tiliv** [comment]
The URLs in the feed itself are leading to 404s now.  Whatever system is building the atom content should be updated to use this url format:

```
https://playoverwatch.com/en-us/news/patch-notes/pc#patch-60038
```

Notice: `/game/` became `/news/`

**Comment by fbis251** [comment]
@tiliv Thanks the report, I fixed the issue.

For future reference the repo for the feed generator is here: https://github.com/fbis251/overwatch_feed_generator
